import type { Metadata } from "next";
import "./globals.css";
import ProviderQuery from "@/components/QueryClientProvider";
import { Toaster } from "sonner";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { getLangDir } from "rtl-detect-intl";
import { Tajawal } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const tajawal = Tajawal({
  weight: ["300", "400", "500", "700"],
  subsets: ["arabic"],
  display: "swap",
});
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  const direction = getLangDir(locale);

  return (
    <html
      data-mode="light"
      lang={locale}
      dir={direction}
      className={tajawal.className}
    >
      <body className="bg-[#f3f5f6] antialiased dark:bg-[#111113]">
        <NextIntlClientProvider messages={messages}>
          <ProviderQuery>
            <>
              {children}
              <Toaster richColors />
            </>
          </ProviderQuery>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
