import type { Metadata } from "next";
import "./globals.css";
import ProviderQuery from "@/components/QueryClientProvider";
import { Toaster } from "@/components/ui/toaster";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { getLangDir } from "rtl-detect-intl";
// import localFont from "next/font/local";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const tajawal = localFont({
//   src: [
//     { path: "../public/font/Tajawal/Tajawal-Light.ttf", weight: "300" },
//     { path: "../public/font/Tajawal/Tajawal-Regular.ttf", weight: "400" },
//     { path: "../public/font/Tajawal/Tajawal-Medium.ttf", weight: "500" },
//     { path: "../public/font/Tajawal/Tajawal-Bold.ttf", weight: "700" },
//   ],
//   display: "swap",
// });

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  const direction = getLangDir(locale);

  return (
    <html
      data-mode="light"
      lang={locale}
      dir={direction}
      // className={tajawal.className || ""}
    >
      <body className="bg-[#f3f5f6] antialiased dark:bg-[#111113]">
        <NextIntlClientProvider messages={messages}>
          <ProviderQuery>
            <>
              {children}
              <Toaster />
            </>
          </ProviderQuery>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
