import { getLocale } from "next-intl/server";
import type { Metadata } from "next";

import Header from "@/components/header";
import Sidebar from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <div className="grid gap-3 m-2" style={{ gridTemplateColumns: "auto 1fr" }}>
      <Sidebar lang={locale} />

      <div className="flex flex-col gap-3">
        <Header lang={locale} />
        {children}
      </div>
    </div>
  );
}
